const DATA = [
    {
        skill : 1, 
        accuracy : [
            "Rica", "Laika", "Lushen","Jeogun",
            "Haegang", "Cheongpung", "Hanwul","Mookwol","Han","Gin","Orochi",
            "Susano","Garo","Wolyung","Yeonhong","Chasun","Mihyang","Hwahee",
            "Sylvia","Illianna","Olivia","Emma","Lisa","Cadiz","Thebae","Amarna",
            "Iunu","Avaris","Khmun","Amduat","Wedjat","Imesety","Qebehsenuef","Duamutef",
            "Jaara","Eludia","Teshar","Sigmarus","Perna","Zeratu","Shan","Lagmaron","Taor",
            "Rakan","Nicki","Lora","Charlotte","Anavel","Rica","Ragdoll","Jager","Leo",
            "Chow","XingZhe","SonZhangLao","QitianDasheng","ShiHou","MeiHouWang","Fermion",
            "Artamiel","Eladriel","Ariel","Velajuel","Rahul","Shazam","Ritesh","Chandra",
            "Kumar","Craka","Asima","Ethna","Beth","Raki","Woonsa","Nigong","Pungbaek",
            "Woosa","Chiwu","Lydia","Elenoa","Tiana","Alicia","Brandia","Veromos","Elsharion",
            "Akhamamir","Theomars","Manannan","Pontos","Triton","Poseidon","Okeanos","Isis",
            "Hathor","Bastet","Sekhmet","Nyx","Oberon","Ganymede","Psamathe","Daphnis","MiYing",
            "TianLang","FengYan","MoLong","XiongFei","Alexandra","Eleanor","Diana","Amelia",
            "Helena","Vivachel","Celia","Triana","Sonnet","Harmonia","Leona","Jeanne","Louise",
            "Josephine","Ophilia","Pater","Valantis","Taranys","Abellio","Bellenus","Herteit",
            "Geldnir","Odin","Bolverk","Baleygr","Bella","Emily","Christina","Abigail","Scarlett",
            "Xiana","Narsha","Savannah","Barbara","Masha","Jun","Kaz","Kaito","Tosi","Sige",
            "Woonhak","Hwadam","Woochi","Gildong","Gunpyeong","Isillen","Eluin","Chamie",
            "Arang","Soha","Shihwa","Tilasha","Icasha","Delphoi","Mikene","Atenai","Icares",
            "Mihael","Acasis","Lumirecia","Fria","Isael","Aria","Selena","Izaria","Akia",
            "Liebli","Figaro","Sian","Jojo","Luna","Eva","Sophia","Julie","Clara","Guillaume",
            "Louis","Julien","Luer","Jean","Ran","Pang","Yen","Su","Hwa","Dias","Conrad",
            "Briand","Fedora","Arnold","Grego","Halphas","Fuco","Rigel","Antares","Fei",
            "LiuMei","LingLing","XiaoLin","HongHua","Hrungnir","Mimirr","Hraesvelg",
            "Aegir","Surtr","Frigate","Brig","Barque","Galleon","Carrack","Betta",
            "Molly","Cichlid","Tetra","Platy","Lanett","Lupinus","Lapis","Isabelle",
            "Natalie","Tanya","Stella","Lexy","Dusky","Misty","Windy","Chilling",
            "Smokey","Monte","Tablo","Morris","Reno","Ludo","Martina","Bailey",
            "Zenobia","Sabrina","Maruna","Hyanes","Felleria","Mellia","Herne",
            "Nisha","Trasar","Einheri","Skogul","Bagir","Vidurr","Onyx","Phenaka","Malite",
            "Tanzaite","Kunite","Mirinae","Dongbaek","Yeonhwa","Songseol","Hongyeon","Kumae","Arkajan",
            "Rakaja","Kunda","Tantra","Jultan","Eshir","Shakan","Vigor","Garoche","Gorgo","Lusha",
            "Ramagos","Dagora","Ursha","Janssen","Jansson","Walter","Huga","Geoffrey","Seren","Sia",
            "Seal","Sisroo","Colleen","Camules","Priz","Taharus","Daharenos","Bremis","Sorin","Neal",
            "Aeilene","Elucia","Iselia","Hellea","Kabilla","Prilea","Ramira","Lucasha","Kro","Belladeon",
            "Ramahan","Icaru","Raoq","Decamaron","Sharman","Lukan","Kaimann","Krakdon","Mantura",
            "Elpuria","Ermeda","Shailoq","Fao","Maggi","Groggo","Ragion","Kuhn","Kugo","Varus",
            "Bernard","Jumaline","Shren","Moria","Ellena","Kahli","Haken","Ahman","Dagorr","Gruda",
            "Kungen","Miho","XiaoLing","Naomi","Mina","Mei","Jubelle","Darion","Roid","Allen",
            "Kaien","Loque","Shaffron","Pigma","Yaku","Fairo","Gina","Linda","Silia","Megan",
            "Rebecca","Zinc","Silver","Copper","Nickel","Iron","WeiShin","TienQin","Huan",
            "Mao","XiaoChun","Kamatau","Grotau","Eintau","Urtau","Burentau","Devinodon",
            "Glinodon","Velfinodon","Kernodon","Igmanodon","Kuna","Dona","Mav","Toma","Naki",
            "Basalt","Marble","Olivine","Talc","Granite","Cassie","Loren","Hannah","Sera",
            "Anne","Jackie","Hiro","Lo","Luan","Sin","Karakum","Sahara","Namib","Nubia",
            "Sonora","Crawler","Driller","Crane","Tractor","Bulldozer","Camaryn","Cheryl",
            "Shannon","Kacey","Tatu","Rizak","Teon","Linderman","Konamiya","Cahule","Lamor",
            "Tigresse","Samour","Fran",
            
            ], 
        critd : [
            "Lushen", "Rica", "Zaiross","Laika","Han","Gin","Orochi","Susano","Garo", "Wolyung",
            "Yeonhong","Hwahee","Mihyang","Cadiz","Julianne","Argen","Liesel","Thebae","Iunu",
            "Avaris","Trinity","Akroma","Katarina","Camilla","Vanessa","Grogen","Zerath","Jamire",
            "Verad","Zaiross","Jaara","Eludia","Teshar","Sigmarus","Perna","Zeratu","Shan","Lagmaron",
            "Taor","Rakan","Giana","Seara","Juno","Nicki","Lora","Charlotte","Anavel","Rica","Ragdoll",
            "Jager","Leo","Chow","XingZhe","SonZhangLao","QitianDasheng","ShiHou","MeiHouWang",
            "Fermion","Artamiel","Velajuel","Rahul","Shazam","Ritesh","Chandra","Kumar","Craka",
            "Asima","Ethna","Beth","Raki","Pungbaek","Woosa","Lydia","Elenoa","Tiana","Alicia",
            "Brandia","Veromos","Elsharion","Akhamamir","Theomars","Manannan","Poseidon","Nyx",
            "Oberon","Ganymede","Psamathe","Daphnis","MiYing","Eleanor","Diana","Helena","Vivachel",
            "Celia","Triana","Sonnet","Harmonia","Leona","Josephine","Pater","Taranys","Bellenus",
            "Herteit","Geldnir","Odin","Baleygr","Bella","Emily","Christina","Abigail","Scarlett",
            "Eirgar","Beelzebub","Lucifer","Mephisto","Belial","Bael","Xiana","Narsha","Savannah",
            "Barbara","Masha","Jun","Kaz","Kaito","Tosi","Bethony","Chris","Ardella","Sharron",
            "Cassandra","Woonhak","Woochi","Gildong","Gunpyeong","Isillen","Lucien","Erwin",
            "Eluin","Adrian","Kamiya","Chamie","Arang","Soha","Shihwa","Aschubel","Eredas",
            "Shimitae","Tyron","Baretta","Isael","Aria","Selena","Izaria","Akia","Liebli",
            "Figaro","Sian","Jojo","Luna","Eva","Sophia","Julie","Clara","Guillaume","Louis",
            "Julien","Jean","Rasheed","Ran","Pang","Yen","Su","Hwa","Conrad","Grego","Fuco",
            "Rigel","Antares","Fei","LiuMei","LingLing","XiaoLin","HongHua","Bering","Dover",
            "Taurus","Malaka","Zibrolta","Hrungnir","Mimirr","Hraesvelg","Aegir","Surtr",
            "Frigate","Brig","Barque","Galleon","Carrack","Betta","Molly","Cichlid","Platy",
            "Lanett","Iris","Lupinus","Lapis","Astar","Isabelle","Natalie","Tanya","Stella",
            "Lexy","Karl","Lucas","Logan","Ryan","Trevor","Dusky","Misty","Windy","Chilling",
            "Smokey","Monte","Tablo","Morris","Reno","Ludo","Belita","Deva","Melissa","Talia",
            "Shaina","Martina","Bailey","Zenobia","Sabrina","Maruna","Einheri","Bagir","Vidurr",
            "Dragunov","Magnum","Carbine","Covenant","Carcano","Onyx","Phenaka","Malite","Tanzaite",
            "Kunite","Mirinae","Dongbaek","Yeonhwa","Songseol","Hongyeon","Kumae","Arkajan","Rakaja",
            "Kunda","Tantra","Eshir","Shakan","Vigor","Garoche","Gorgo","Lusha","Ramagos","Dagora",
            "Ursha","Seren","Seal","Camules","Priz","Taharus","Daharenos","Bremis","Sorin","Neal",
            "Iselia","Hellea","Kabilla","Prilea","Ramira","Lucasha","Kro","Ramahan","Raoq","Decamaron",
            "Sharman","Lukan","Kaimann","Krakdon","Mantura","Elpuria","Ermeda","Shailoq","Fao","Maggi",
            "Groggo","Ragion","Kuhn","Kugo","Varus","Shamann","Bernard","Kahn","Spectra","Drogan",
            "Eludain","Anduril","Purian","Tagaros","Jumaline","Shren","Moria","Ellena","Kahli",
            "Haken","Ahman","Dagorr","Gruda","Kungen","Mara","Lyn","Hina","Ellin","Ceres","Miho",
            "XiaoLing","Naomi","Mina","Mei","Jubelle","Darion","Roid","Allen","Kaien","Jamie","Walkers",
            "Roger","Wayne","Randy","Loque","Shaffron","Pigma","Yaku","Fairo","Silia","Thrain","Prom",
            "Hiva","Hemos","Sath","Zinc","Silver","Copper","Nickel","Iron","WeiShin","TienQin","Huan",
            "Mao","XiaoChun","Kamatau","Grotau","Eintau","Urtau","Burentau","Devinodon","Glinodon",
            "Velfinodon","Kernodon","Igmanodon","Hannam","Baekdu","Suri","Gangchun","Nangrim","Kuna",
            "Dona","Mav","Toma","Naki","Marble","Cassie","Loren","Hannah","Sera","Anne","Calicus",
            "Rumicus","Zephicus","Aqcus","Ignicus","Jackie","Hiro","Lo","Luan","Sin","Karakum",
            "Sahara","Namib","Nubia","Sonora","Crawler","Driller","Crane","Tractor","Bulldozer",
            "Camaryn","Tatu","Cogma","Fynn","Ralph","Taru","Garok","Fran",
        ],
        recovery : [
            "Laika", "Garo","Cadiz","Julianne","Argen","Liesel","Verdehile","Jager","MeiHouWang",
            "Jeanne","MiYing","Eirgar","Kamiya","Rasheed","Iona","Michelle","Rina","Chloe","Trevor",
            "Garoche","Shumar","Shamar","Gamir","Tarq","Sieq","Shamann","Miho","Chacha","Shushu",
            "Chichi","Lulu","Lala",
        ]
    }, 
    {
        skill : 2,
        accuracy : [
        "Verad","Zaiross","Rica", "Haegang", "Cheongpung", "Mookwol","Han","Gin","Orochi","Susano","Garo",
        "Yeonhong","Mihyang","Sylvia","Emma","Lisa","Cadiz","Julianne","Argen","Liesel","Amarna","Iunu",
        "Avaris","Amduat","Imesety","Qebehsenuef","Akroma","Camilla","Vanessa","Grogen","Jamire",
        "Eludia","Sigmarus","Giana","Laima","Seara","Praha","Juno","Lora","Charlotte","Rica","XingZhe",
        "SonZhangLao","QitianDasheng","ShiHou","MeiHouWang","Fermion","Velajuel","Craka","Asima","Ethna",
        "Beth","Raki","Woonsa","Pungbaek","Chiwu","Elenoa","Brandia","Veromos","Elsharion","Akhamamir",
        "Theomars","Manannan","Pontos","Triton","Poseidon","Okeanos","Isis","Hathor","Bastet","Sekhmet",
        "Nyx","Psamathe","Daphnis","TianLang","MoLong","Alexandra","Eleanor","Diana","Amelia","Helena",
        "Celia","Sonnet","Leona","Josephine","Ophilia","Valantis","Bellenus","Bella","Emily","Christina",
        "Abigail","Scarlett","Eirgar","Xiana","Narsha","Savannah","Barbara","Masha","Jun","Sige",
        "Bethony","Sharron","Cassandra","Woonhak","Hwadam","Woochi","Gildong","Gunpyeong","Lucien",
        "Erwin","Eluin","Adrian","Kroa","Raviti","Remy","Kamiya","Shihwa","Tilasha","Icasha",
        "Delphoi","Mikene","Atenai","Aschubel","Eredas","Shimitae","Tyron","Baretta","Mihael",
        "Lumirecia","Isael","Aria","Selena","Izaria","Akia","Liebli","Figaro","Lushen","Sian","Jojo",
        "Luna","Eva","Sophia","Julie","Clara","Guillaume","Louis","Julien","Luer","Jean","Ran","Pang",
        "Yen","Su","Hwa","Dias","Conrad","Briand","Fedora","Arnold","Grego","Halphas","Fuco","Rigel",
        "Antares","Fei","LiuMei","LingLing","XiaoLin","HongHua","Gemini","Orion","Draco","Bering",
        "Dover","Taurus","Malaka","Zibrolta","Hrungnir","Mimirr","Hraesvelg","Aegir","Surtr","Frigate",
        "Brig","Barque","Galleon","Carrack","Lanett","Iris","Lupinus","Lapis","Astar","Natalie",
        "Stella","Lexy","Lucas","Logan","Ryan","Dusky","Misty","Smokey","Monte","Tablo","Morris",
        "Reno","Ludo","Deva","Melissa","Shaina","Martina","Sabrina","Maruna","Hyanes","Mellia",
        "Einheri","Bagir","Vidurr","Magnum","Covenant","Onyx","Phenaka","Malite","Tanzaite",
        "Kunite","Mirinae","Dongbaek","Yeonhwa","Songseol","Hongyeon","Kumae","Arkajan","Rakaja","Kunda",
        "Tantra","Jultan","Shakan","Garoche","Gorgo","Ursha","Janssen","Walter","Geoffrey","Seren",
        "Sia","Seal","Sisroo","Colleen","Sorin","Iselia","Hellea","Ramira","Belladeon","Ramahan",
        "Decamaron","Sharman","Lukan","Kaimann","Krakdon","Mantura","Elpuria","Ermeda","Shailoq","Fao",
        "Maggi","Kuhn","Kugo","Varus","Bernard","Kahn","Drogan","Eludain","Anduril","Purian","Tagaros",
        "Jumaline","Moria","Haken","Mara","Ellin","Ceres","Miho","Naomi","Mina","Jubelle","Darion","Roid",
        "Allen","Kaien","Walkers","Roger","Loque","Yaku","Fairo","Gina","Linda","Silia","Megan","Rebecca",
        "Thrain","Hemos","Zinc","Silver","Copper","Nickel","Iron","Grotau","Burentau","Devinodon",
        "Velfinodon","Kernodon","Hannam","Baekdu","Suri","Gangchun","Nangrim","Kuna","Dona","Mav","Toma",
        "Naki","Marble","Olivine","Granite","Cassie","Loren","Hannah","Calicus","Rumicus","Zephicus",
        "Aqcus","Ignicus","Jackie","Hiro","Lo","Luan","Sin","Karakum","Nubia","Sonora","Crawler",
        "Driller","Crane","Tractor","Bulldozer","Camaryn","Cheryl","Shannon","Kacey","Tatu","Fynn",
        "Taru","Rizak","Linderman","Cahule","Lamor","Tigresse","Samour",
    
        ],
        critd : [
            "Cheongpung","Han","Gin","Orochi","Susano","Garo","Yeonhong","Cadiz","Julianne",
            "Argen","Liesel","Thebae","Iunu","Avaris","Khmun","Amduat","Imesety","Trinity","Akroma",
            "Katarina","Camilla","Vanessa","Grogen","Jamire","Verad","Zaiross","Jaara","Eludia",
            "Teshar","Sigmarus","Perna","Shan","Lagmaron","Taor","Lora","Charlotte","Rica","Ragdoll",
            "Jager","Leo","Chow","Laika","XingZhe","SonZhangLao","QitianDasheng","ShiHou","MeiHouWang",
            "Fermion","Velajuel","Craka","Asima","Ethna","Beth","Raki","Nigong","Pungbaek","Woosa",
            "Lydia","Elenoa","Tiana","Alicia","Brandia","Veromos","Elsharion","Akhamamir","Theomars",
            "Manannan","Poseidon","Nyx","Psamathe","Daphnis","TianLang","MoLong","Diana","Helena",
            "Leona","Josephine","Ophilia","Pater","Valantis","Taranys","Abellio","Bellenus","Bella",
            "Emily","Christina","Abigail","Scarlett","Eirgar","Beelzebub","Lucifer","Mephisto",
            "Belial","Bael","Xiana","Narsha","Savannah","Barbara","Masha","Jun","Kaz","Kaito",
            "Tosi","Sige","Bethony","Chris","Ardella","Sharron","Cassandra","Woonhak","Woochi",
            "Gildong","Gunpyeong","Lucien","Erwin","Eluin","Adrian","Chamie","Arang","Soha",
            "Delphoi","Aschubel","Eredas","Shimitae","Tyron","Icares","Acasis","Fria","Isael",
            "Aria","Selena","Izaria","Akia","Figaro","Lushen","Luna","Eva","Sophia","Julie",
            "Clara","Guillaume","Louis","Julien","Jean","Ran","Pang","Yen","Su","Hwa","Conrad",
            "Grego","Fuco","Rigel","Antares","Fei","LiuMei","LingLing","XiaoLin","HongHua",
            "Bering","Zibrolta","Hrungnir","Mimirr","Hraesvelg","Aegir","Surtr","Frigate",
            "Brig","Barque","Galleon","Carrack","Lanett","Iris","Lupinus","Lapis","Astar",
            "Natalie","Stella","Lexy","Karl","Lucas","Logan","Ryan","Trevor","Misty",
            "Smokey","Monte","Tablo","Morris","Reno","Ludo","Deva","Melissa","Shaina","Martina",
            "Sabrina","Maruna","Einheri","Bagir","Vidurr","Magnum","Covenant","Onyx","Phenaka","Malite",
            "Tanzaite","Kunite","Mirinae","Songseol","Kumae","Arkajan","Rakaja","Kunda","Tantra","Shakan",
            "Garoche","Gorgo","Ursha","Janssen","Jansson","Walter","Huga","Geoffrey","Seren","Priz",
            "Daharenos","Bremis","Shumar","Shamar","Gamir","Tarq","Sieq","Sorin","Hellea","Kabilla",
            "Prilea","Ramira","Lucasha","Kro","Belladeon","Ramahan","Icaru","Raoq","Decamaron","Sharman",
            "Lukan","Kaimann","Krakdon","Mantura","Elpuria","Ermeda","Shailoq","Fao","Maggi","Kuhn",
            "Kugo","Varus","Shamann","Bernard","Kahn","Spectra","Drogan","Eludain","Anduril","Purian",
            "Tagaros","Jumaline","Shren","Moria","Ellena","Kahli","Haken","Ahman","Gruda","Kungen",
            "Mara","Lyn","Hina","Ellin","Ceres","Miho","Naomi","Mina","Jubelle","Darion","Roid","Allen",
            "Kaien","Jamie","Walkers","Roger","Wayne","Randy","Loque","Yaku","Fairo","Linda","Silia",
            "Prom","Hiva","Sath","Zinc","Silver","Copper","Nickel","Iron","WeiShin","XiaoChun","Kamatau",
            "Grotau","Eintau","Urtau","Burentau","Devinodon","Glinodon","Velfinodon","Kernodon","Igmanodon",
            "Hannam","Baekdu","Suri","Gangchun","Nangrim","Dona","Toma","Naki","Marble","Olivine","Granite",
            "Cassie","Loren","Hannah","Sera","Anne","Calicus","Rumicus","Zephicus","Aqcus","Ignicus",
            "Jackie","Hiro","Lo","Luan","Sin","Karakum","Nubia","Sonora","Driller","Bulldozer","Camaryn",
            "Tatu","Cogma","Ralph","Garok",
        ],
        recovery : [
            "Eladriel","Garo","Laika","Wolyung","Chasun","Hwahee","Thebae","Iunu","Khmun",
            "Trinity","Katarina","Zerath","Nicki","Anavel","Jager","MeiHouWang","Artamiel",
            "Ariel","Shazam","Ritesh","Kumar","Nigong","Woosa","Vivachel","Triana","Harmonia",
            "Pater","Taranys","Abellio","Chamie","Arang","Soha","Tilasha","Mikene","Atenai",
            "Icares","Acasis","Rasheed","Iona","Michelle","Rina","Chloe","Hrungnir","Surtr",
            "Betta","Platy","Trevor","Felleria","Herne","Nisha","Onyx","Phenaka","Malite",
            "Tanzaite","Kunite","Eshir","Vigor","Garoche","Lusha","Ramagos","Dagora","Neal",
            "Aeilene","Elucia","Miho","Shaffron","Pigma","TienQin","Huan","Mao","Kamatau",
            "Eintau","Urtau","Kuna","Mav","Basalt","Talc","Chacha","Shushu","Chichi","Lulu",
            "Lala","Fran",
        ]
    }, 
    
    {
        skill : 3,
        accuracy : [
            "Verad","Zaiross", "Rica","Jeogun", "Cheongpung","Han","Gin","Orochi",
            "Olivia","Cadiz","Thebae","Duamutef","Jaara","Eludia","Sigmarus","Shan",
            "Lagmaron","Taor","Rakan","Giana","Praha","Nicki","Charlotte","Anavel",
            "Rica","Leo","SonZhangLao","QitianDasheng","ShiHou","Fermion","Rahul",
            "Shazam","Ritesh","Chandra","Kumar","Asima","Ethna","Beth","Woonsa","Chiwu",
            "Alicia","Brandia","Elsharion","Triton","Poseidon","Okeanos","Isis","Hathor",
            "Sekhmet","Daphnis","XiongFei","Celia","Sonnet","Jeanne","Pater","Taranys",
            "Abellio","Bellenus","Emily","Abigail","Scarlett","Bael","Xiana","Jun","Kaz",
            "Kaito","Chris","Sharron","Cassandra","Woonhak","Woochi","Gildong","Gunpyeong",
            "Eluin","Kamiya","Arang","Soha","Shihwa","Aschubel","Eredas","Shimitae","Tyron",
            "Baretta","Fria","Isael","Aria","Selena","Izaria","Akia","Figaro","Jojo","Luna",
            "Eva","Sophia","Clara","Julien","Luer","Ran","Su","Hwa","Arnold","Fuco","LiuMei",
            "LingLing","Korona","Gemini","Aquila","Orion","Bering","Dover","Taurus","Malaka",
            "Zibrolta","Mimirr","Aegir","Brig","Galleon","Cichlid","Platy","Iris","Lupinus",
            "Lapis","Natalie","Tanya","Stella","Logan","Ryan","Chilling","Smokey","Belita",
            "Deva","Shaina","Martina","Zenobia","Maruna","Hyanes","Mellia","Herne","Nisha",
            "Bagir","Carcano","Phenaka","Tanzaite","Songseol","Jultan","Eshir","Shakan",
            "Vigor","Gorgo","Ursha","Walter","Geoffrey","Seren","Sia","Seal","Sisroo","Taharus",
            "Shamar","Sorin","Elucia","Iselia","Hellea","Prilea","Lucasha","Kro","Kaimann","Krakdon",
            "Mantura","Shailoq","Fao","Spectra","Drogan","Eludain","Anduril","Tagaros","Ellena","Dagorr",
            "Kungen","Mara","Lyn","Hina","Ellin","Roid","Kaien","Walkers","Loque","Pigma","Yaku",
            "Fairo","Gina","Silia","Thrain","Prom","Hemos","Sath","Zinc","Silver","Nickel","WeiShin",
            "TienQin","Huan","Urtau","Burentau","Velfinodon","Igmanodon","Suri","Gangchun","Kuna","Naki",
            "Basalt","Granite","Loren","Hannah","Sera","Anne","Aqcus","Ignicus","Jackie","Hiro","Namib",
            "Nubia","Camaryn","Kacey","Cogma","Fynn","Chacha",
        ],
        critd : [
            "Lushen", "Cheongpung","Hanwul","Han","Gin","Orochi","Wolyung","Hwahee",
            "Argen","Liesel","Thebae","Trinity","Katarina","Grogen","Zerath","Verad",
            "Zaiross","Eludia","Teshar","Sigmarus","Lagmaron","Taor","Rakan","Seara",
            "Nicki","Lora","Charlotte","Anavel","Rica","SonZhangLao","QitianDasheng",
            "ShiHou","Rahul","Shazam","Ritesh","Chandra","Kumar","Asima","Ethna","Beth",
            "Raki","Woonsa","Pungbaek","Alicia","Brandia","Akhamamir","Poseidon","Sekhmet",
            "Oberon","Ganymede","Daphnis","XiongFei","Sonnet","Bellenus","Baleygr","Emily",
            "Abigail","Scarlett","Bael","Xiana","Jun","Kaz","Kaito","Tosi","Sige","Bethony",
            "Chris","Sharron","Cassandra","Gildong","Gunpyeong","Eluin","Kamiya","Arang",
            "Soha","Shihwa","Eredas","Shimitae","Tyron","Isael","Aria","Selena","Izaria",
            "Akia","Jojo","Luna","Sophia","Julie","Clara","Julien","Ran","Su","Conrad",
            "Fei","LiuMei","LingLing","XiaoLin","HongHua","Korona","Bering","Dover",
            "Taurus","Malaka","Zibrolta","Mimirr","Hraesvelg","Aegir","Surtr","Brig",
            "Barque","Carrack","Cichlid","Platy","Lanett","Lupinus","Lapis","Isabelle",
            "Natalie","Tanya","Stella","Karl","Logan","Ryan","Smokey","Reno","Belita",
            "Melissa","Talia","Bailey","Zenobia","Maruna","Einheri","Bagir","Covenant",
            "Eshir","Vigor","Lusha","Walter","Seren","Sia","Seal","Sisroo","Taharus",
            "Shamar","Sorin","Aeilene","Iselia","Hellea","Prilea","Ramira","Lucasha","Kro",
            "Ramahan","Kaimann","Krakdon","Mantura","Shailoq","Kahn","Eludain","Anduril",
            "Tagaros","Ellena","Dagorr","Kungen","Mara","Lyn","Hina","Ellin","Ceres","Mei",
            "Roid","Walkers","Roger","Loque","Shaffron","Pigma","Yaku","Fairo","Gina","Linda",
            "Silia","Prom","Hiva","Hemos","Zinc","Silver","Copper","WeiShin","TienQin","Huan",
            "Mao","XiaoChun","Urtau","Burentau","Hannam","Baekdu","Suri","Kuna","Toma","Basalt",
            "Marble","Granite","Cassie","Hannah","Sera","Anne","Calicus","Ignicus","Jackie",
            "Hiro","Lo","Driller","Bulldozer","Camaryn","Kacey","Tatu","Cogma","Fynn","Ralph",
            "Taru","Chichi","Lala",
        ],
        recovery : [
            "Perna","Yeonhong","Chasun","Mihyang","Emma","Cadiz","Amarna","Camilla","Rakan",
            "Praha","Chow","Ariel","Woonsa","Veromos","MiYing","Helena","Harmonia","Louise",
            "Abellio","Geldnir","Bolverk","Delphoi","Atenai","Icares","Mihael","Lumirecia",
            "Izaria","Hrungnir","Mimirr","Hraesvelg","Aegir","Surtr","Betta","Molly","Tetra",
            "Lanett","Iris","Lapis","Felleria","Hongyeon","Rakaja","Tantra","Garoche","Ramagos",
            "Jansson","Geoffrey","Colleen","Belladeon","Lukan","Varus","Jumaline","Shren","Ahman",
            "XiaoLing","Rebecca","Grotau","Eintau","Urtau","Rumicus","Aqcus","Luan","Camaryn",
            "Teon","Konamiya","Shushu","Chichi","Lulu","Fran",
        ]
    },
    
    {
        skill : 4,
        accuracy : [
            "None"
        ],
        critd : [
            "Sige","Tosi","Jun","Kaz","Kaito","Bella","Christina",   
        ],
        recovery : [
            "None"
        ]
    },
    
    {
        skill : 5,
        counter : [
            "Verdehile","XingZhe","QitianDasheng","ShiHou","MeiHouWang","Fermion","Artamiel","Rahul",
            "Chandra","FengYan","MiYing","XiongFei","Eleanor","Leona","Josephine","Valantis","Isillen",
            "Isael","Aria","Selena","Izaria","Akia","Liebli","Ran","Yen","Hwa","Grego","Halphas","Fuco",
            "Rigel","Antares","Fei","LiuMei","LingLing","XiaoLin","Lanett","Chilling","Arkajan","Dagora",
            "Ursha","Icaru","Ragion","Miho","XiaoLing","Mei","Shaffron","Pigma","Devinodon","Luan",
        ],
        atktogether : [
         "Sylvia","Lisa","Belita","Deva","Melissa","Talia","Shaina","Martina","Bailey","Zenobia",
         "Sabrina","Maruna","Seren","Sia","Tarq","Kro","Icaru","Raoq","Moria","Granite",
        ],
        bombd : [
            "Seara","Giana","Liebli","Sian","Jojo","Dover","Taurus","Malaka",
        ],
        lifedrain : ["Cadiz","Verdehile","Julianne","Argen","Liesel","Thebae","Trinity","Katarina",
                     "Rakan","Jager","Laika","MeiHouWang","MiYing","MoLong","Pater","Taranys",
                     "Abellio","Eirgar","Kamiya","Chamie","Arang","Soha","Icares","Izaria","Hrungnir",
                     "Surtr","Lanett","Lapis","Trevor","Miho","Eintau","Aqcus","Camaryn","Chichi",
                    ],
        defense : ["Imesety","Olivia","Emma","Wedjat","Duamutef","Lora","Ragdoll","Jager","MeiHouWang",
        "Fermion","Artamiel","Ariel","Elsharion","FengYan","Leona","Taranys","Abellio","Bellenus",
        "Raviti","Mihael","Dias","Molly","Misty","Martina","Einheri","Bagir","Vidurr","Onyx","Phenaka",
        "Malite","Tanzaite","Kunite","Arkajan","Lusha","Ramagos","Dagora","Decamaron","Sharman","Lukan",
        "Kaimann","Krakdon","Elpuria","Maggi","Groggo","Ragion","Kuhn","Kugo","Varus","Kaien","Randy",
        "Megan","Zinc","Silver","Copper","Nickel","Iron","Devinodon","Glinodon","Velfinodon","Kernodon","Igmanodon",
        "Basalt","Talc","Jackie","Luan","Sin","Crawler","Driller","Crane","Tractor","Bulldozer","Shannon",
                    ],
        attack : ["Lushen","Jeogun","Wolyung","Chasun","Mihyang","Hwahee","Qebehsenuef","Perna","Katarina",
        "Zaiross","Jaara","Eludia","Garo","Laika","Teshar","Sigmarus","Trinity","Akroma","Grogen",
        "Zeratu","Taor","Lagmaron","Shan","Rakan","Giana","Seara","Nicki","Lora","Charlotte",
        "Anavel","Rica","Ragdoll","Jager","ShiHou","MeiHouWang","Asima","Ethna","Alicia","Brandia",
        "Pungbaek","Elsharion","Akhamamir","Theomars","Manannan","Poseidon","Bastet","Oberon",
        "Psamathe","Daphnis","MiYing","Leona","Odin","Herteit","Baleygr","Bella","Emily","Abigail",
        "Scarlett","Eirgar","Lucifer","Mephisto","Belial","Bael","Xiana","Narsha","Savannah","Barbara",
        "Masha","Sige","Tosi","Jun","Kaz","Kaito","Bethony","Chris","Ardella","Sharron","Cassandra",
        "Gildong","Gunpyeong","Isillen","Lucien","Erwin","Eluin","Adrian","Dova","Kamiya","Chamie",
        "Arang","Shihwa","Soha","Shimitae","Tyron","Isael","Aria","Selena","Izaria","Akia","Liebli",
        "Figaro","Lushen","Sian","Jojo","Luna","Eva","Sophia","Julie","Guillaume","Julien","Luer",
        "Jean","Ran","Pang","Yen","Su","Hwa","Conrad","Grego","Fuco","Rigel","Antares","Fei","LiuMei",
        "LingLing","HongHua","XiaoLin","Korona","Gemini","Aquila","Draco","Bering","Dover","Taurus",
        "Malaka","Zibrolta","Hrungnir","Mimirr","Hraesvelg","Aegir","Surtr","Brig","Barque","Galleon",
        "Carrack","Lanett","Iris","Lupinus","Lapis","Astar","Isabelle","Natalie","Tanya","Stella",
        "Lexy","Karl","Lucas","Logan","Ryan","Trevor","Dusky","Misty","Windy","Chilling","Smokey",
        "Morris","Reno","Ludo","Belita","Deva","Melissa","Talia","Shaina","Martina","Bailey","Zenobia",
        "Sabrina","Maruna","Vidurr","Dragunov","Magnum","Carbine","Covenant","Carcano","Mirinae",
        "Tantra","Seren","Sia","Colleen","Camules","Priz","Taharus","Daharenos","Bremis","Shumar",
        "Shamar","Gamir","Tarq","Sieq","Sorin","Neal","Aeilene","Elucia","Iselia","Hellea","Kabilla",
        "Prilea","Ramira","Lucasha","Kro","Raoq","Elpuria","Drogan","Eludain","Anduril","Purian","Tagaros",
        "Jumaline","Shren","Moria","Ellena","Kahli","Haken","Dagorr","Mara","Lyn","Hina","Ellin","Miho",
        "XiaoLing","Naomi","Mina","Mei","Jamie","Walkers","Roger","Wayne","Loque","Shaffron","Pigma","Yaku",
        "Fairo","Megan","Prom","WeiShin","TienQin","Huan","Mao","XiaoChun","Kamatau","Eintau","Glinodon",
        "Igmanodon","Hannam","Baekdu","Suri","Gangchun","Nangrim","Toma","Cassie","Loren","Hannah","Anne",
        "Calicus","Rumicus","Zephicus","Aqcus","Ignicus","Shannon","Cogma","Fynn","Ralph","Taru","Garok",
        "Teon","Konamiya","Fran",
                ],
        speed : ["Jeogun","Hanwul","Han","Gin","Orochi","Susano","Garo","Shan",
                "Amduat","Imesety","Lagmaron","Taor","QitianDasheng","Rahul","Shazam",
                "Ritesh","Chandra","Kumar","Elsharion","Theomars","Nephthys","Bastet",
                "Sekhmet","Ganymede","Isis","Hathor","Daphnis","TianLang","FengYan",
                "Alexandra","Vivachel","Celia","Triana","Sonnet","Harmonia","Xiana","Narsha",
                "Savannah","Barbara","Masha","Kaz","Tosi","Kaito","Chris","Ardella","Woonhak",
                "Isillen","Erwin","Adrian","Kroa","Dova","Racuni","Shimitae","Tyron","Luer",
                "Chloe","Ran","Pang","Yen","Su","Hwa","Fei","Korona","Aquila","Orion","Draco",
                "Dover","Hrungnir","Mimirr","Hraesvelg","Aegir","Surtr","Frigate","Galleon",
                "Carrack","Betta","Molly","Tetra","Platy","Iris","Lupinus","Astar","Isabelle",
                "Tanya","Stella","Dusky","Misty","Windy","Chilling","Smokey","Tablo","Reno",
                "Martina","Bailey","Felleria","Mellia","Trasar","Skogul","Magnum","Mirinae",
                "Eshir","Vigor","Janssen","Shumar","Tarq","Kabilla","Varus","Shamann","Bernard",
                "Kahn","Spectra","Purian","Kahli","Wayne","Gina","Megan","Mao","Grotau","Hannam",
                "Baekdu","Mav","Zephicus","Lo","Crane","Fynn","Cogma","Ralph","Taru","Garok",
                "Teon","Konamiya","Cahule","Fran",
                ],
        reflect : ["Lydia","Alexandra","Kumae","Kunda","Jultan","Camules","Fao","Maggi","Velfinodon",
        "Sonora",
                    ],
    },
    
    ]
    
    
    
    
    export default DATA