const MONSTERS = {


    Jeogun: ["Fire","Support"],
    Haegang: ["Water","Support"],
   Cheongpung : ["Wind","Attack"],
    Hanwul: ["Light","Attack"],
    Mookwol: ["Dark","Support"],

    Masha : ["Fire","Attack"],
    Barbara : ["Water","Attack"],
    Savannah : ["Wind","Attack"],
    Narsha: ["Light","Attack"],
    Xiana : ["Dark","Attack"],

    Bael: ["Fire","Attack"],
    Belial: ["Water","Attack"],
    Mephisto: ["Wind","HP"],
    Lucifer: ["Light","HP"],
    Beelzebub: ["Dark","Attack"],

    Eirgar: ["Dark","Attack"],

    Scarlett: ["Fire","Attack"],
    Abigail: ["Water","Attack"],
    Christina: ["Wind","Attack"],
    Emily: ["Light","Attack"],
    Bella: ["Dark","Attack"],

    Baleygr: ["Fire","Attack"],
    Bolverk: ["Water","HP"],
    Odin: ["Wind","Attack"],
    Geldnir: ["Light","HP"],
    Herteit: ["Dark","Attack"],

    Bellenus: ["Fire","Defense"],
    Abellio: ["Water","Defense"],
    Taranys: ["Wind","Defense"],
    Valantis: ["Light","HP"],
    Pater: ["Dark","HP"],

    Ophilia: ["Fire","HP"],
    Josephine: ["Water","HP"],
    Louise: ["Wind","Support"],
    Jeanne: ["Light","HP"],
    Leona: ["Dark","Defense"],

    Helena: ["Fire","HP"],
    Amelia: ["Water","HP"],
    Diana: ["Wind","HP"],
    Eleanor: ["Light","HP"],
    Alexandra: ["Dark","HP"],

    Harmonia: ["Fire","Support"],
    Sonnet: ["Water","Support"],
    Triana: ["Wind","Support"],
    Celia: ["Light","Support"],
    Vivachel: ["Dark","Support"],

    XiongFei : ["Fire","Defense"],
    MoLong: ["Water","HP"],
    FengYan: ["Wind","Defense"],
    TianLang: ["Light","HP"],
    MiYing: ["Dark","Attack"],

    Daphnis : ["Fire","Attack"],
    Psamathe: ["Water","Attack"],
    Ganymede: ["Wind","Suport"],
    Oberon: ["Light","Attack"],
    Nyx: ["Dark","Support"],

    Sekhmet: ["Fire","Support"],
    Bastet: ["Water","Support"],
    Hathor: ["Wind","Support"],
    Isis: ["Light","Support"],
    Nephthys: ["Dark","Support"],

    Khmun: ["Fire","Support"],
    Avaris: ["Water","Attack"],
    Iunu: ["Wind","Attack"],
    Amarna: ["Light","Support"],
    Thebae: ["Dark","HP"],

    Lisa: ["Fire","Support"],
    Emma: ["Water","Support"],
    Olivia: ["Wind","Support"],
    Illianna: ["Light","Support"],
    Sylvia: ["Dark","Support"],

    Okeanos: ["Fire","Attack"],
    Poseidon: ["Water","Attack"],
    Triton: ["Wind","Defense"],
    Pontos: ["Light","Support"],
    Manannan: ["Dark","Attack"],

    Tesarion: ["Fire","HP"],
    Theomars: ["Water","Attack"],
    Akhamamir: ["Wind","Attack"],
    Elsharion: ["Light","Attack"],
    Veromos: ["Dark","Support"],

    Brandia: ["Fire","Attack"],
    Alicia: ["Water","Attack"],
    Tiana: ["Wind","Support"],
    Elenoa: ["Light","Support"],
    Lydia: ["Dark","Attack"],

    Chiwu: ["Fire","HP"],
    Woosa: ["Water","HP"],
    Pungbaek: ["Wind","HP"],
    Nigong: ["Light","HP"],
    Woonsa: ["Dark","HP"],

    Hwahee: ["Fire","Attack"],
    Mihyang: ["Water","Support"],
    Chasun: ["Wind","Support"],
    Yeonhong: ["Light","Support"],
    Wolyung: ["Dark","Attack"],

    Raki: ["Fire","Attack"],
    Beth: ["Water","Attack"],
    Ethna: ["Wind","Attack"],
    Asima: ["Light","Attack"],
    Craka: ["Dark","Support"],

    Kumar: ["Fire","HP"],
    Chandra: ["Water","HP"],
    Ritesh: ["Wind","HP"],
    Shazam: ["Light","HP"],
    Rahul: ["Dark","HP"],

    Velajuel: ["Fire","Support"],
    Ariel: ["Water","Support"],
    Eladriel: ["Wind","Support"],
    Artamiel: ["Light","Support"],
    Fermion: ["Dark","Defense"],

    MeiHouWang: ["Fire","Defense"],
    ShiHou: ["Water","Attack"],
    XingZhe: ["Wind","HP"],
    QitianDasheng: ["Light","Support"],
    SonZhangLao: ["Dark","HP"],

    Laika: ["Fire","Attack"],
    Chow: ["Water","HP"],
    Leo: ["Wind","Support"],
    Jager: ["Light","HP"],
    Ragdoll: ["Dark","Support"],

    Rica: ["Fire","Attack"],
    Anavel: ["Water","Support"],
    Charlotte: ["Wind","Attack"],
    Lora: ["Light","HP"],
    Nicki: ["Dark","Attack"],

    Juno: ["Fire","Support"],
    Praha: ["Water","Support"],
    Seara: ["Wind","Attack"],
    Laima: ["Light","Support"],
    Giana: ["Dark","Attack"],

    Verdehile: ["Fire","Attack"],
    Liesel: ["Water","HP"],
    Argen: ["Wind","Attack"],
    Julianne: ["Light","Attack"],
    Cadiz: ["Dark","Attack"],

    Rakan: ["Fire","HP"],
    Taor: ["Water","Attack"],
    Lagmaron: ["Wind","Attack"],
    Shan: ["Light","Attack"],
    Zeratu: ["Dark","Attack"],

    Perna: ["Fire","HP"],
    Sigmarus: ["Water","Attack"],
    Teshar: ["Wind","Attack"],
    Eludia: ["Light","Attack"],
    Jaara: ["Dark","Attack"],

    Zaiross: ["Fire","Attack"],
    Verad: ["Water","Defense"],
    Jamire: ["Wind","Support"],
    Zerath: ["Light","HP"],
    Grogen: ["Dark","Attack"],

    Vanessa: ["Fire","Support"],
    Camilla: ["Water","HP"],
    Katarina: ["Wind","Attack"],
    Akroma: ["Light","Defense"],
    Trinity: ["Dark","HP"],

    Garo: ["Fire","Attack"],
    Susano: ["Water","Attack"],
    Orochi: ["Wind","HP"],
    Gin: ["Light","Attack"],
    Han: ["Dark","HP"],

    Duamutef: ["Fire","Defense"],
    Qebehsenuef: ["Water","Support"],
    Imesety: ["Wind","Support"],
    Wedjat: ["Light","Attack"],
    Amduat: ["Dark","Support"],

    Hongyeon: ["Fire","Support"],
    Songseol: ["Water","Support"],
    Yeonhwa: ["Wind","Support"],
    Dongbaek: ["Light","Support"],
    Mirinae: ["Dark","Support"],

    Kunite: ["Fire","Defense"],
    Tanzaite: ["Water","Defense"],
    Malite: ["Wind","Defense"],
    Phenaka: ["Light","Defense"],
    Onyx: ["Dark","Defense"],

    Carcano: ["Fire","Attack"],
    Covenant: ["Water","Attack"],
    Carbine: ["Wind","Attack"],
    Magnum: ["Light","Attack"],
    Dragunov: ["Dark","Attack"],

    Vidurr: ["Fire","Defense"],
    Bagir: ["Water","Defense"],
    Skogul: ["Wind","HP"],
    Einheri: ["Light","Defense"],
    Trasar: ["Dark","HP"],

    Nisha: ["Fire","Support"],
    Herne: ["Water","Support"],
    Mellia: ["Wind","Support"],
    Felleria: ["Light","Support"],
    Hyanes: ["Dark","Support"],

    Maruna: ["Fire","Attack"],
    Sabrina: ["Water","Attack"],
    Zenobia: ["Wind","Attack"],
    Bailey: ["Light","Attack"],
    Martina: ["Dark","Attack"],

    Shaina: ["Fire","Attack"],
    Talia: ["Water","Attack"],
    Melissa: ["Wind","Attack"],
    Deva: ["Light","Attack"],
    Belita: ["Dark","Attack"],

    Ludo: ["Fire","Attack"],
    Reno: ["Water","Attack"],
    Morris: ["Wind","Support"],
    Tablo: ["Light","Support"],
    Monte: ["Dark","Support"],

    Adrian: ["Fire","Support"],
    Eluin: ["Water","Attack"],
    Erwin: ["Wind","Attack"],
    Lucien: ["Light","Attack"],
    Isillen: ["Dark","Attack"],

    Smokey: ["Fire","Attack"],
    Chilling: ["Water","Attack"],
    Windy: ["Wind","Support"],
    Misty: ["Light","Attack"],
    Dusky: ["Dark","Attack"],

    Trevor: ["Fire","Attack"],
    Ryan: ["Water","Attack"],
    Logan: ["Wind","Attack"],
    Lucas: ["Light","Attack"],
    Karl: ["Dark","Attack"],

    Lexy: ["Fire","Attack"],
    Stella: ["Water","Attack"],
    Tanya: ["Wind","Attack"],
    Natalie: ["Light","Attack"],
    Isabelle: ["Dark","Attack"],

    Astar: ["Fire","Attack"],
    Lapis: ["Water","Attack"],
    Lupinus: ["Wind","HP"],
    Iris: ["Light","Attack"],
    Lanett: ["Dark","Defense"],

    Platy: ["Fire","Support"],
    Tetra: ["Water","Support"],
    Cichlid: ["Wind","Support"],
    Molly: ["Light","Support"],
    Betta: ["Dark","Support"],

    Carrack: ["Fire","Attack"],
    Galleon: ["Water","HP"],
    Barque: ["Wind","Attack"],
    Brig: ["Light","Brig"],
    Frigate: ["Dark","Frigate"],

    Surtr: ["Fire","Attack"],
    Aegir: ["Water","Attack"],
    Hraesvelg: ["Wind","Attack"],
    Mimirr: ["Light","Attack"],
    Hrungnir: ["Dark","Attack"],

    Zibrolta: ["Fire","Attack"],
    Malaka: ["Water","Attack"],
    Taurus: ["Wind","Attack"],
    Dover: ["Light","Attack"],
    Bering: ["Dark","Attack"],

    Draco: ["Fire","Support"],
    Orion: ["Water","Support"],
    Aquila: ["Wind","Attack"],
    Gemini: ["Light","Attack"],
    Korona: ["Dark","Support"],

    HongHua: ["Fire","HP"],
    XiaoLin: ["Water","Attack"],
    LingLing: ["Wind","Attack"],
    LiuMei: ["Light","HP"],
    Fei: ["Dark","Attack"],

    Jun: ["Fire","Attack"],
    Kaz: ["Water","Attack"],
    Kaito: ["Wind","Attack"],
    Tosi: ["Light","Attack"],
    Sige: ["Dark","Attack"],

    Antares: ["Fire","Attack"],
    Rigel: ["Water","Support"],
    Fuco: ["Wind","HP"],
    Halphas: ["Light","Defense"],
    Grego: ["Dark","HP"],

    Arnold: ["Fire","HP"],
    Fedora: ["Water","Support"],
    Briand: ["Wind","HP"],
    Conrad: ["Light","Attack"],
    Dias: ["Dark","Dias"],

    Hwa: ["Fire","Attack"],
    Su: ["Water","Attack"],
    Yen: ["Wind","Attack"],
    Pang: ["Light","Attack"],
    Ran: ["Dark","Attack"],

    Cassandra: ["Fire","Attack"],
    Sharron: ["Water","Attack"],
    Ardella: ["Wind","Attack"],
    Chris: ["Light","Attack"],
    Bethony: ["Dark","Attack"],

    Jean: ["Fire","Attack"],
    Luer: ["Water","Support"],
    Julien: ["Wind","Attack"],
    Louis: ["Light","Support"],
    Guillaume: ["Dark","Attack"],

    Clara: ["Fire","Attack"],
    Julie: ["Water","Attack"],
    Sophia: ["Wind","Attack"],
    Eva: ["Light","Attack"],
    Luna: ["Dark","Attack"],

    Jojo: ["Fire","Defense"],
    Sian: ["Water","Attack"],
    Lushen: ["Wind","Attack"],
    Figaro: ["Light","HP"],
    Liebli: ["Dark","Attack"],

    Akia: ["Fire","Attack"],
    Izaria: ["Water","Attack"],
    Selena: ["Wind","Attack"],
    Aria: ["Light","Attack"],
    Isael: ["Dark","Attack"],

    Fria: ["Fire","Support"],
    Lumirecia: ["Water","Support"],
    Acasis: ["Wind","Support"],
    Mihael: ["Light","Support"],
    Icares: ["Dark","Attack"],

    Baretta: ["Fire","Attack"],
    Tyron: ["Water","Attack"],
    Shimitae: ["Wind","Attack"],
    Eredas: ["Light","HP"],
    Aschubel: ["Dark","Attack"],

    Atenai: ["Fire","Support"],
    Mikene: ["Water","Support"],
    Delphoi: ["Wind","Support"],
    Icasha: ["Light","Support"],
    Tilasha: ["Dark","Support"],

    Shihwa: ["Fire","Attack"],
    Soha: ["Water","Attack"],
    Arang: ["Wind","Attack"],
    Chamie: ["Light","Attack"],
    Kamiya: ["Dark","Attack"],

    Bulldozer: ["Fire","HP"],
    Tractor : ["Water","Defense"],
    Crane: ["Wind","Defense"],
    Driller: ["Light","HP"],
    Crawler: ["Dark","Defense"],

    Sonora: ["Fire","HP"],
    Nubia: ["Water","HP"],
    Namib: ["Wind","HP"],
    Sahara: ["Light","HP"],
    Karakum: ["Dark","HP"],

    Sin: ["Fire","Defense"],
    Luan: ["Water","Defense"],
    Lo: ["Wind","Attack"],
    Hiro: ["Light","HP"],
    Jackie: ["Dark","Defense"],

    Racuni: ["Fire","Support"],
    Remy: ["Water","Support"],
    Raviti: ["Wind","Support"],
    Dova: ["Light","Support"],
    Kroa: ["Dark","Support"],

    Gunpyeong: ["Fire","Attack"],
    Gildong: ["Water","Attack"],
    Woochi: ["Wind","Defense"],
    Hwadam: ["Light","HP"],
    Woonhak: ["Dark","HP"],

    Chloe: ["Fire","Support"],
    Rina: ["Water","Support"],
    Michelle: ["Wind","Support"],
    Iona: ["Light","Support"],
    Rasheed: ["Dark","HP"],

    Ignicus: ["Fire","HP"],
    Aqcus: ["Water","Attack"],
    Zephicus: ["Wind","HP"],
    Rumicus: ["Light","Attack"],
    Calicus: ["Dark","Attack"],

    Anne: ["Fire","Attack"],
    Sera: ["Water","Attack"],
    Hannah: ["Wind","Attack"],
    Loren: ["Light","Attack"],
    Cassie: ["Dark","Attack"],

    Granite: ["Fire","HP"],
    Talc: ["Water","HP"],
    Olivine: ["Wind","Defense"],
    Marble: ["Light","HP"],
    Basalt: ["Dark","Defense"],

    Naki: ["Fire","HP"],
    Toma: ["Water","Attack"],
    Mav: ["Wind","HP"],
    Dona: ["Light","Support"],
    Kuna: ["Dark","HP"],

    Nangrim: ["Fire","Attack"],
    Gangchun: ["Water","Attack"],
    Suri: ["Wind","Attack"],
    Baekdu: ["Light","Attack"],
    Hannam: ["Dark","Attack"],

    Igmanodon: ["Fire","Defense"],
    Kernodon: ["Water","Defense"],
    Velfinodon: ["Wind","Defense"],
    Glinodon: ["Light","Defense"],
    Devinodon: ["Dark","Defense"],

    Burentau: ["Fire","HP"],
    Urtau: ["Water","HP"],
    Eintau: ["Wind","HP"],
    Grotau: ["Light","HP"],
    Kamatau: ["Dark","HP"],

    XiaoChun: ["Fire","Attack"],
    Mao: ["Water","Attack"],
    Huan: ["Wind","Attack"],
    TienQin: ["Light","Attack"],
    WeiShin: ["Dark","Attack"],

    Iron: ["Fire","Defense"],
    Nickel: ["Water","Defense"],
    Copper: ["Wind","Defense"],
    Silver: ["Light","Defense"],
    Zinc: ["Dark","Defense"],

    Sath: ["Fire","Attack"],
    Hemos: ["Water","Attack"],
    Hiva: ["Wind","Attack"],
    Prom: ["Light","Attack"],
    Thrain: ["Dark","Attack"],

    Rebecca: ["Fire","Support"],
    Megan: ["Water","Support"],
    Silia: ["Wind","Attack"],
    Linda: ["Light","Attack"],
    Gina: ["Dark","Attack"],

    Fairo: ["Fire","Attack"],
    Yaku: ["Water","Attack"],
    Pigma: ["Wind","Defense"],
    Shaffron: ["Light","Defense"],
    Loque: ["Dark","Attack"],

    Randy: ["Fire","Attack"],
    Wayne: ["Water","Attack"],
    Roger: ["Wind","Attack"],
    Walkers: ["Light","Attack"],
    Jamie: ["Dark","Attack"],

    Kaien: ["Fire","Defense"],
    Allen: ["Water","HP"],
    Roid: ["Wind","HP"],
    Darion: ["Light","Defense"],
    Jubelle: ["Dark","Defense"],
    
    Mei: ["Fire","HP"],
    Mina: ["Water","Attack"],
    Naomi: ["Wind","Attack"],
    XiaoLing: ["Light","HP"],
    Miho: ["Dark","Attack"],
  
    Ceres: ["Fire","Attack"],
    Ellin: ["Water","Attack"],
    Hina: ["Wind","Attack"],
    Lyn: ["Light","Attack"],
    Mara: ["Dark","Attack"],

    Geoffrey: ["Fire","Defense"],
    Huga: ["Water","Attack"],
    Walter: ["Wind","HP"],
    Jansson: ["Light","Defense"],
    Janssen: ["Dark","HP"],

    Garoche: ["Fire","HP"],
    Vigor: ["Water","HP"],
    Shakan: ["Wind","Defense"],
    Eshir: ["Light","HP"],
    Jultan: ["Dark","HP"],

    Kungen: ["Fire","HP"],
    Gruda: ["Water","HP"],
    Dagorr: ["Wind","Attack"],
    Ahman: ["Light","HP"],
    Haken: ["Dark","HP"],

    Colleen: ["Fire","Support"],
    Sisroo: ["Water","Support"],
    Seal: ["Wind","Support"],
    Sia: ["Light","Attack"],
    Seren: ["Dark","Attack"],

    Kahli: ["Fire","Attack"],
    Ellena: ["Water","Attack"],
    Moria: ["Wind","Attack"],
    Shren: ["Light","Support"],
    Jumaline: ["Dark","Attack"],

    Tagaros: ["Fire","Attack"],
    Purian: ["Water","Attack"],
    Anduril: ["Wind","Attack"],
    Eludain: ["Light","Attack"],
    Drogan: ["Dark","Attack"],

    Spectra: ["Fire","Support"],
    Kahn: ["Water","HP"],
    Bernard: ["Wind","Support"],
    Shamann: ["Light","Defense"],
    Varus: ["Dark","Defense"],

    Kugo: ["Fire","Defense"],
    Kuhn: ["Water","Defense"],
    Ragion: ["Wind","Defense"],
    Groggo: ["Light","Defense"],
    Maggi: ["Dark","Defense"],

    Fao: ["Fire","HP"],
    Shailoq: ["Water","HP"],
    Ermeda: ["Wind","HP"],
    Elpuria: ["Light","HP"],
    Mantura: ["Dark","HP"],

    Raoq: ["Fire","Attack"],
    Icaru: ["Water","Defense"],
    Ramahan: ["Wind","Defense"],
    Belladeon: ["Light","Defense"],
    Kro: ["Dark","Attack"],

    Bremis: ["Fire","Attack"],
    Daharenos: ["Water","Attack"],
    Taharus: ["Wind","Attack"],
    Priz: ["Light","Attack"],
    Camules: ["Dark","Attack"],

    Sieq: ["Fire","Attack"],
    Tarq: ["Water","Attack"],
    Gamir: ["Wind","Attack"],
    Shamar: ["Light","Attack"],
    Shumar: ["Dark","Attack"],

    Lucasha: ["Fire","Attack"],
    Ramira: ["Water","Attack"],
    Prilea: ["Wind","Attack"],
    Kabilla: ["Light","Attack"],
    Hellea: ["Dark","Attack"],

    Tantra: ["Fire","HP"],
    Kunda: ["Water","Defense"],
    Rakaja: ["Wind","Defense"],
    Arkajan: ["Light","Defense"],
    Kumae: ["Dark","HP"],

    Lala: ["Fire","Support"],
    Lulu: ["Water","Support"],
    Chichi: ["Wind","Support"],
    Shushu: ["Light","Support"],
    Chacha: ["Dark","Support"],

    Krakdon: ["Fire","Defense"],
    Kaimann: ["Water","Defense"],
    Lukan: ["Wind","Defense"],
    Sharman: ["Light","Defense"],
    Decamaron: ["Dark","Defense"],

    Cahule: ["Fire","Support"],
    Konamiya: ["Water","Support"],
    Linderman: ["Wind","Support"],
    Teon: ["Light","Support"],
    Rizak: ["Dark","Support"],

    Ursha: ["Fire","HP"],
    Dagora: ["Water","HP"],
    Ramagos: ["Wind","HP"],
    Lusha: ["Light","HP"],
    Gorgo: ["Dark","HP"],

    Tatu: ["Fire","Attack"],
    Kacey: ["Water","Support"],
    Shannon: ["Wind","Support"],
    Cheryl: ["Light","Support"],
    Camaryn: ["Dark","Attack"],

    Iselia: ["Fire","Attack"],
    Elucia: ["Water","Support"],
    Aeilene: ["Wind","Support"],
    Neal: ["Light","Support"],
    Sorin: ["Dark","Attack"],

    Lamor: ["Fire","Support"],
    Tigresse: ["Water","Support"],
    Samour: ["Wind","Support"],
    Varis: ["Light","Support"],
    Havana: ["Dark","Support"],

    Cogma : ["Fire","Attack"],
    Fynn : ["Water","Attack"],
    Ralph : ["Wind","Attack"],
    Taru : ["Light","Attack"],
    Garok : ["Dark", "Attack"],

    
    Fran : ["Light","Support"],
    
    None : ["None","None"]

    
    }


    export default MONSTERS